<?xml version="1.0" encoding="UTF-8"?>
<!--
	Copyright The WildFly Authors
	SPDX-License-Identifier: Apache-2.0
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.wildfly.clustering</groupId>
		<artifactId>wildfly-clustering-container</artifactId>
		<version>12.0.0.Beta2</version>
	</parent>

	<artifactId>wildfly-clustering-container-arquillian</artifactId>
	<packaging>jar</packaging>

	<name>${project.container}: Arquillian</name>

	<properties>
		<project.module.name>org.wildfly.clustering.container.arquillian</project.module.name>
		<tomcat.http.port>8080</tomcat.http.port>
		<tomcat.jmx.port>8089</tomcat.jmx.port>
		<tomcat.admin.username>admin</tomcat.admin.username>
		<tomcat.admin.password>admin</tomcat.admin.password>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.kohsuke.metainf-services</groupId>
			<artifactId>metainf-services</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.wildfly.clustering</groupId>
			<artifactId>wildfly-clustering-arquillian</artifactId>
		</dependency>
		<dependency>
			<groupId>org.wildfly.clustering</groupId>
			<artifactId>wildfly-clustering-container-spi</artifactId>
		</dependency>

		<dependency>
			<groupId>org.jboss.arquillian.container</groupId>
			<artifactId>arquillian-container-spi</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jboss.arquillian.container</groupId>
			<artifactId>arquillian-container-impl-base</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jboss.arquillian.test</groupId>
			<artifactId>arquillian-test-spi</artifactId>
		</dependency>

		<dependency>
			<groupId>org.jboss.arquillian.container</groupId>
			<artifactId>arquillian-tomcat-remote-10</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.arquillian.junit5</groupId>
			<artifactId>arquillian-junit5-container</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-suite-api</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<build>
		<testResources>
			<testResource>
				<directory>src/test/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>**</include>
				</includes>
			</testResource>
		</testResources>
	</build>
</project>
