name: Backport
run-name: Backport

on:
  pull_request_target:
    types:
      - closed

jobs:
  backport:
    name: Backport
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        # Enumerate branches to which we will attempt to backport
        branch:
          - 10.x
    if: contains(github.event.pull_request.labels.*.name, vars.BACKPORT_LABEL) == true
    runs-on: ubuntu-latest
    steps:
      - id: create-app-token
        name: Create GitHub App installation access token
        # Per https://github.com/actions/create-github-app-token#create-a-token-for-the-current-repository
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          owner: ${{ github.repository_owner }}
          permission-contents: write
          permission-pull-requests: write
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - id: app-user
        name: Determine user ID of GitHub App installation
        env:
          GH_TOKEN: ${{ steps.create-app-token.outputs.token }}
        # Per https://github.com/actions/create-github-app-token#create-a-git-committer-string-for-an-app-installation
        run: echo "id=$(gh api "/users/${{ steps.create-app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"

      - id: git-configure
        name: Configure git with GitHub app author
        run: |
          git config --global user.name "${{ steps.create-app-token.outputs.app-slug }}[bot]"
          git config --global user.email "${{ steps.app-user.outputs.id }}+${{ steps.create-app-token.outputs.app-slug }}[bot]@users.noreply.github.com"
          echo "name=$(git config get user.name)" >> "$GITHUB_OUTPUT"
          echo "email=$(git config get user.email)" >> "$GITHUB_OUTPUT"

      - id: git-checkout
        name: ${{ format('Checkout {0} branch', matrix.branch) }}
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          # Checkout backport target branch
          ref: ${{ matrix.branch }}
          token: ${{ steps.create-app-token.outputs.token }}

      - id: prepare-backport
        name: Prepare backport branch
        if: (github.event.pull_request.merged == true) && (github.event.pull_request.base.ref == github.event.pull_request.base.repo.default_branch)
        run: git cherry-pick -x $(git rev-list --reverse --no-merges ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.merge_commit_sha }})

      - id: create-backport-pull-request
        name: Create backport pull request
        if: (github.event.pull_request.merged == true) && (github.event.pull_request.base.ref == github.event.pull_request.base.repo.default_branch)
        uses: peter-evans/create-pull-request@v8
        with:
          base: ${{ matrix.branch }}
          branch: ${{ format('backport-{0}-{1}', matrix.branch, github.event.pull_request.number) }}
          committer: ${{ steps.git-configure.outputs.email }}
          label: ${{ vars.BACKPORT_LABEL }}
          title: ${{ format('[{0}] {1}', matrix.branch, github.event.pull_request.title) }}
          body: ${{ format('Backport of {0}', github.event.pull_request.url) }}
          token: ${{ steps.create-app-token.outputs.token }}
          sign-commits: true

      - id: delete-backport-branch
        name: Delete backport branch
        if: (github.event.pull_request.base.ref == matrix.branch) && (github.event.pull_request.base.repo.full_name == github.event.pull_request.head.repo.full_name)
        run: |
          git push origin --delete ${{ github.event.pull_request.head.ref }}
