name: Backport

on:
  pull_request_target:
    types:
    - closed

jobs:
  backport:
    strategy:
      matrix:
        branch:
        - { source: main, target: 10.x }
    if: (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, vars.BACKPORT_LABEL) == true)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ${{ matrix.branch.target }}
      if: github.event.pull_request.base.ref == matrix.branch.source
      uses: actions/checkout@v6
      with:
        ref: ${{ matrix.branch.target }}

    - name: Backport ${{ github.event.pull_request.number }} to ${{ matrix.branch.target }}
      if: github.event.pull_request.base.ref == matrix.branch.source
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout -b backport-${{ matrix.branch.target }}-${{ github.event.pull_request.number }}
        git cherry-pick -x | git rev-list --reverse --no-merges ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.merge_commit_sha }}
        gh pr create --base ${{ matrix.branch.target }} --title "[${{ matrix.branch.target }}] ${{ github.event.pull_request.title }} --body "Backport of ${{ github.event.pull_request.url }}"
