name: Backport

on:
  pull_request_target:
    types:
    - closed

jobs:
  backport:
    name: Backport
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        branch:
        - 10.x
    if: (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, vars.BACKPORT_LABEL) == true)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ${{ matrix.branch }}
      if: github.event.pull_request.base.ref == github.event.pull_request.base.repo.default_branch
      uses: actions/checkout@v6
      with:
        ref: ${{ matrix.branch }}

    - name: Backport ${{ github.event.pull_request.number }} to ${{ matrix.branch }}
      if: github.event.pull_request.base.ref == github.event.pull_request.base.repo.default_branch
      env:
        BACKPORT_BRANCH: backport-${{ matrix.branch }}-${{ github.event.pull_request.number }}
        # For use by GitHub CLI
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Per https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout -b ${{ env.BACKPORT_BRANCH }} -t origin/${{ matrix.branch }}
        git fetch origin ${{ matrix.branch.source }}
        git cherry-pick -x $(git rev-list --reverse --no-merges ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.merge_commit_sha }})
        git push origin
        gh pr create --base ${{ matrix.branch }} --head ${{ env.BACKPORT_BRANCH }} --label ${{ vars.BACKPORT_LABEL }} --title "[${{ matrix.branch }}] ${{ github.event.pull_request.title }}" --body "Backport of ${{ github.event.pull_request.url }}"

    - name: Delete ${{ matrix.branch }} backport branch
      if: (github.event.pull_request.base.ref == matrix.branch) && (github.event.pull_request.base.repo.full_name == github.event.pull_request.head.repo.full_name)
      run: |
        git push origin --delete ${{ github.event.pull_request.head.ref }}
