name: Verify

on:
  pull_request_target:
    types:
    - opened
    - reopened
    - synchronize

jobs:
  verify:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        java:
        - 25
    name: Build with Java ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_GOAL: ${{ case(contains(github.event.pull_request.labels.*.name, vars.VALIDATE_ONLY_LABEL) == true, 'validate', 'verify -P lts') }}
      PR_JSON: ${{ toJSON(github.event.pull_request) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        java-version: |
          17
          21
          25
        distribution: temurin
        cache: maven

    - name: Maven ${{ env.MAVEN_GOAL }}
      run: mvn --batch-mode --no-transfer-progress ${{ env.MAVEN_GOAL }}
