name: Verify

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        java:
        - 25
    name: Java ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      VALIDATE_ONLY_LABEL: unverified
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        java-version: |
          17
          21
          25
        distribution: temurin
        cache: maven
    - name: Validate
      run: mvn --batch-mode --no-transfer-progress validate
    - name: Verify
      if: (github.event_name != 'pull_request') || contains(github.event.pull_request.labels.*.name, env.VALIDATE_ONLY_LABEL) == false
      run: mvn --batch-mode --no-transfer-progress verify -P lts
